language: php
sudo: false
php:
    - 7.1
    - 7.2
    - 7.3
env:
    matrix:
        - ILLUMINATE_VERSION=5.5.* ORCHESTRA_TESTBENCH_VERSION=3.5.*

addons:
    code_climate:
        repo_token:
            secure: "RnnIrzTkNYZn5ocWr8dIenHBFk/cwzF4AUvgHMZQlsHtgFclIX204xMEHL0bF+DR1XJNYqNE7Dk7Oqt1bt62ht7eTmOsOKhxcoDirbjp1We0o24ZyRIoso9qUg4YoDlc0K+QPx/u6OZHRkLny2+BHKPpLDV3MMSBo+n8MZJ1WiVqBpuHmlT3WV4kfeBpZoLDxbfVfFlczP27BV9M6anlT6ntsdR6HmqHruFQKvN+ulH5VFbBrQEEHsq/+zpcepS6rumoDhvD2BxjHGV046/GQSEiAcCEwsmgeSFilz2QqVXEx/xlJVqwCSxoih63e7uBfEgRPTuQ3CEsKVhnPzy1T72xqRsHOoYpQO//nXSER5LFlW7Sul2W1Zvzbco6LKQ4RXrdVzh3olCzBo8Ze4nkiHdsdUHkK0mM9ckR3WWWbFpmK0R4eACwzrpZC+7GUZmG+Xzipa716Bx9kT3XtOzlzOSWRlsLDlBML9LnkK6V1QOhgeotl6QqXcTWxnzPB9Dbjm0gF0Tpv+DSn9zRMvR2P1eKr7JFGiy4/FZ0W0aMd1HZPYRI7vwBHABRx2sgo7p5QFEoP/VmC73qRBVmCemPbF4R9hp0hhGrV7HHfb2DL1NjagkHdPDAIteHXpDc37EyP6ZH2JS/svCXTjq9HlpOnWaT85mq6EQxHZi7Xva46QY="

before_install:
    - composer require illuminate/config:${ILLUMINATE_VERSION} --no-update
    - composer require illuminate/console:${ILLUMINATE_VERSION} --no-update
    - composer require illuminate/contracts:${ILLUMINATE_VERSION} --no-update
    - composer require illuminate/container:${ILLUMINATE_VERSION} --no-update
    - composer require illuminate/database:${ILLUMINATE_VERSION} --no-update
    - composer require --dev orchestra/testbench:${ORCHESTRA_TESTBENCH_VERSION} --no-update
    - if [[ "${ILLUMINATE_VERSION}" == "5.7.*" ]]; then composer require --dev mockery/mockery --no-update; fi;

install:
    - cp .env.testing .env
    - composer self-update
    - composer install --prefer-source --no-interaction
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: ILLUMINATE_VERSION=5.6.* ORCHESTRA_TESTBENCH_VERSION=3.6.*
        - php: 7.1
          env: ILLUMINATE_VERSION=5.7.* ORCHESTRA_TESTBENCH_VERSION=3.7.*
        - php: 7.1
          env: ILLUMINATE_VERSION=5.8.* ORCHESTRA_TESTBENCH_VERSION=3.8.*
        - php: 7.2
          env: ILLUMINATE_VERSION=5.6.* ORCHESTRA_TESTBENCH_VERSION=3.6.*
        - php: 7.2
          env: ILLUMINATE_VERSION=5.7.* ORCHESTRA_TESTBENCH_VERSION=3.7.*
        - php: 7.2
          env: ILLUMINATE_VERSION=5.8.* ORCHESTRA_TESTBENCH_VERSION=3.8.*
        - php: 7.2
          env: ILLUMINATE_VERSION=6.* ORCHESTRA_TESTBENCH_VERSION=4.*
        - php: 7.3
          env: ILLUMINATE_VERSION=5.6.* ORCHESTRA_TESTBENCH_VERSION=3.6.*
        - php: 7.3
          env: ILLUMINATE_VERSION=5.7.* ORCHESTRA_TESTBENCH_VERSION=3.7.*
        - php: 7.3
          env: ILLUMINATE_VERSION=5.8.* ORCHESTRA_TESTBENCH_VERSION=3.8.*
        - php: 7.3
          env: ILLUMINATE_VERSION=6.* ORCHESTRA_TESTBENCH_VERSION=4.*
        - php: 7.3
          env: ILLUMINATE_VERSION=7.* ORCHESTRA_TESTBENCH_VERSION=5.*

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: always